name: "🐛 Bug Report"
description: 提交一个问题 / Report a bug
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Kuingsmile
body:
  - type: markdown
    attributes:
      value: |+
        ## PicList Issue 模板

        请依照该模板来提交，否则将会被关闭。
        **提问之前请注意你看过 FAQ、文档以及那些被关闭的 issues。否则同样的提问也会被关闭！**

        Please submit according to this template, otherwise it will be closed.
        **Before asking a question, please note that you have read the FAQ, Doc, and those closed issues. Otherwise the same question will also be closed! **

  - type: checkboxes
    id: read
    attributes:
      label: 前置阅读 | Pre-reading
      description: 我已经自行查找、阅读以下内容（阅读了请打勾） | I have searched and read the following on my own (Please tick after reading)
      options:
        - label: "[文档/Doc](https://piclist.cn/)"
          required: true
        - label: "[Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)"
          required: true
        - label: "[FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)"
          required: true
  - type: input
    id: version
    attributes:
      label: PicList的版本 | PicList Version
      placeholder: 例如 v0.0.1
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 系统信息 | System Information
      options:
        - Windows
        - Mac
        - Mac(arm64)
        - Linux
        - All
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 问题重现 | Bug reproduce
      description: 请复述Bug重现流程，必要时附图 | Please tell me the bug reproduction process, attach pictures if necessary
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 相关日志 | Logs
      description: 请附上 PicList 的相关报错日志（用文本的形式）。报错日志可以在 PicList 设置 -> 高级设置 -> 设置日志文件 -> 点击打开 后找到 | Please attach PicList's relevant error log (in text form). The error log can be found in PicList Settings -> Advanced -> Set Log File -> Click to Open
  - type: markdown
    attributes:
      value: |
        最后，喜欢 PicList 的话不妨给它点个 star~
        Finally, if you like PicList, give it a star~
